services:
  - type: web
    name: coin-listing-notifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8123195608:AAFH7uHI3d5qCslSA5A8dn7i2or1Tg4pCHg
      - key: TELEGRAM_CHAT_ID
        value: "-1002379561191"
