services:
  - type: web
    name: coin-listing-notifier
    env: python
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "替换为你的 Bot Token"
      - key: TELEGRAM_CHAT_ID
        value: "替换为你的 Chat ID"
